[colors.bright]
black = "#404040"
blue = "#4e9fb1"
cyan = "#42717b"
green = "#a0cf5d"
magenta = "#8542ff"
red = "#d23d3d"
white = "#000000"
yellow = "#f39d21"

[colors.cursor]
cursor = "#f39d21"
text = "#000000"

# Colors (Blood Moon)
[colors]
  [colors.primary]
    background = '#10100E'
    foreground = '#C6C6C4'
  [colors.normal]
    black = '#10100E'
    red = '#C40233'
    green = '#009F6B'
    yellow = '#FFD700'
    blue = '#0087BD'
    magenta = '#9A4EAE'
    cyan = '#20B2AA'
    white = '#C6C6C4'


# # Colors (Oceanic Next)
# [colors]
#   [colors.primary]
#     background = '#1b2b34'
#     foreground = '#d8dee9'
#   [colors.normal]
#     black = '#343d46'
#     red = '#EC5f67'
#     green = '#99C794'
#     yellow = '#FAC863'
#     blue = '#6699cc'
#     magenta = '#c594c5'
#     cyan = '#5fb3b3'
#     white = '#d8dee9'

# # Colors (Gruvbox light)
# [colors]
#   [colors.primary]
#     background = '#fbf1c7'
#     foreground = '#3c3836'
#   [colors.normal]
#     black = '#fbf1c7'
#     red = '#cc241d'
#     green = '#98971a'
#     yellow = '#d79921'
#     blue = '#458588'
#     magenta = '#b16286'
#     cyan = '#689d6a'
#     white = '#7c6f64'


# #Colors(rif's default colors)
# [colors.normal]
# black = "#000000"
# blue = "#7dc1cf"
# cyan = "#6d878d"
# green = "#b8d68c"
# magenta = "#9b64fb"
# red = "#e84f4f"
# white = "#dddddd"
# yellow = "#e1aa5d"
#
# [colors.primary]
# background = "#000000"
# foreground = "#ffffff"

[colors.vi_mode_cursor]
cursor = "#c3abca"
text = "#000000"

[font]
size = 11

[font.bold]
family = "terminal-font"
style = "Bold"

[font.bold_italic]
family = "terminal-font"
style = "Bold Italic"

[font.italic]
family = "terminal-font"
style = "Italic"

[font.normal]
family = "terminal-font"
style = "Regular"

[font.offset]
x = 2
y = 1

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[scrolling]
history = 50000

[window]
opacity = 0.9
decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[window.dimensions]
columns = 98
lines = 31

[window.padding]
x = 7
y = 7





